export enum caseType {
  DEFAULT_CASE = 'DEFAULT_CASE',
  OPTION_SELECTED_CASE = 'OPTION_SELECTED_CASE',
  RIGHT_ANSWER_CASE = 'RIGHT_ANSWER_CASE',
  WRONG_ANSWER_CASE = 'WRONG_ANSWER_CASE',
  NONE = 'None',
}
